---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    field.cattle.io/description: minio test instance
  finalizers:
  labels:
    harvesterhci.io/creator: terraform-provider-kubevirt
    harvesterhci.io/vmName: hrv-minio01
    tag.harvesterhci.io/role: server
    tag.harvesterhci.io/ssh-user: ubuntu
  name: hrv-minio01
  namespace: harvester-public
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        harvesterhci.io/sshNames: '[]'
        harvesterhci.io/waitForLeaseInterfaceNames: '["enp1s0"]'
      creationTimestamp: null
      labels:
        harvesterhci.io/creator: terraform-provider-kubevirt
        harvesterhci.io/vmName: hrv-minio01
        tag.harvesterhci.io/role: server
        tag.harvesterhci.io/ssh-user: ubuntu
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: network.harvesterhci.io/mgmt
                operator: In
                values:
                - "true"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: harvesterhci.io/creator
                  operator: Exists
              topologyKey: kubernetes.io/hostname
            weight: 100
      architecture: amd64
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: root-fs
          - disk:
              bus: virtio
            name: minio-data
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - bridge: {}
            macAddress: 32:66:94:e4:be:12
            model: virtio
            name: enp1s0
        firmware:
          bootloader:
            efi:
              secureBoot: false
        machine:
          type: q35
        memory:
          guest: 3996Mi
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 125m
            memory: 2730Mi
      evictionStrategy: LiveMigrate
      networks:
      - multus:
          networkName: hp-untagged
        name: enp1s0
      terminationGracePeriodSeconds: 120
      volumes:
      - name: root-fs
        persistentVolumeClaim:
          claimName: hrv-minio01-root-fs-448r8
      - name: minio-data
        persistentVolumeClaim:
          claimName: hrv-minio01-minio-data-h76g2
      - cloudInitNoCloud:
          networkData: |
            network:
              version: 2
              ethernets:
                enp1s0:
                  dhcp4: true
                gateway4: 10.1.250.1
                nameservers:
                  addresses:
                    - 10.1.250.222
                    - 10.1.20.20
                    - 8.8.8.8
                    - 8.8.4.4
          userData: |
            #cloud-config
            password: molecule
            chpasswd: { expire: False }
            ssh_pwauth: True
            package_update: true
            package_upgrade: true

            chpasswd:
              list: |
                ubuntu:ubuntu
              expire: false

            packages:
              - curl
              - git
              - openssl
              - python3
              - python3-apt
              - qemu-guest-agent
              - wget
            runcmd:
              - - systemctl
                - enable
                - --now
                - qemu-guest-agent.service
            ssh_authorized_keys:
              - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF6YpLo8hwTiyiEicC9W3RriqJrNxyymPYgMN6GCGoTF ubuntu@harvester-minio


            disk_setup:
              /dev/vdb:  # Assuming /dev/vdb will be where this secondary disk attaches
                table_type: "gpt"
                layout: true
                overwrite: false

            fs_setup:
              - device: /dev/vdb
                filesystem: "xfs"
                label: "minio-data"

            mounts:
              - [ /dev/vdb, /mnt/minio-data ]
        name: cloudinitdisk
