---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log | default(false) }}"
  vars:
    ansible_python_interpreter: /Users/CoryClose/PythonVEnvs/molecule-plugins/.venv/bin/python3
    # TODO Make this exist
    ssh_identity_file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/ssh_key"
    kubeconfig_path: "{{ molecule_yml.driver.kubeconfig | realpath }}"
    instances: "{{ molecule_yml.platforms }}"
    default_run_id: "{{ lookup('password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=5, seed=now(fmt='%s')) }}"
    default_run_config:
      run_id: "{{ molecule_yaml.driver.run_id | default(default_run_id) }}"
      run_prefix: "{{ molecule_yaml.driver.run_prefix | default('molecule-') }}"

    run_config_path: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/run-config.yml"
    run_config_from_file: "{{ (lookup('file', run_config_path, errors='ignore') or '{}') | from_yaml }}"
    run_config: '{{ default_run_config | combine(run_config_from_file) }}'

  tasks:
    - name: Load Instance Config
      kubevirt_driver_instance_config:
        action: load
        path: "{{ molecule_instance_config }}"
      register: instance_config

    - name: Process Instance and Platform Data
      kubevirt_driver_process_instance_data:
        action: prepare
        instance_config: "{{ instance_config.instance_config }}"
        platform_config: "{{ instances }}"
        run_config: "{{ run_config }}"
      register: instance_data

    - name: Destroy Instance
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        api_version: v1
        kind: VirtualMachine
        namespace: "{{ instance.namespace | default(defaultNamespace) }}"
        state: absent
        definition:
          metadata:
            name: "{{ instance.pod_name }}"
      register: server
      loop: "{{ instance_data.instance_data }}"
      loop_control:
        index_var: instance_index
        loop_var: instance

    # For an explanation of this Loop structure, see Create Secondary Drive(s) task
    # in Create.yml playbook

    - name: Destroy Drive(s)
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        api_version: v1
        kind: PersistentVolumeClaim
        namespace: "{{ instance.namespace | default(defaultNamespace) }}"
        state: absent
        definition:
          metadata:
            name: "{{ disk.name }}"
      loop: "{{ instance_data.instance_data | subelements('pvcs', skip_missing=True) }}"
      loop_control:
        loop_var: instance_and_disk
      vars:
        instance: "{{ instance_and_disk[0] }}"  # The main item
        disk: "{{ instance_and_disk[1] }}"      # The subelement

    # Mandatory configuration for Molecule to function.
    - name: Clear Instance Configs
      ansible.builtin.set_fact:
        instance_conf: { }

    - name: Dump Instance Config
      ansible.builtin.copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
        mode: "0600"
      when: server.changed | default(false) | bool  # noqa no-handler

    - name: Clear Run Config
      ansible.builtin.file:
        path: "{{ run_config_path }}"
        state: absent
